site_name: Fast Turbulence Sim

site_url: https://molinalexei.github.io/fast_turbulence_sim/

nav:
  - Home: 'index.md'
  - API Reference :
      - Abundance : 'references/abundance.md'
      - Binning : 'references/binning.md'
      - Cooling : 'references/cooling.md'
      - Cube : 'references/cube.md'
      - Density : 'references/density.md'
      - Emissivity : 'references/emissivity.md'
      - Projection : 'references/projection.md'
      - Simulation : 'references/simulation.md'
      - Structure Function : 'references/structure_function.md'
      - Temperature : 'references/temperature.md'
      - Turbulence : 'references/turbulence.md'



theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter:
      include_requirejs: True
      include_source: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.astropy.org/en/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://samreay.github.io/ChainConsumer/objects.inv
            - https://num.pyro.ai/en/stable/objects.inv
            - https://dm-haiku.readthedocs.io/en/latest/objects.inv
            - https://python.arviz.org/en/stable/objects.inv
            - https://astropy-regions.readthedocs.io/en/stable/objects.inv
          options:
            members_order: alphabetical
            docstring_section_style: table
            docstring_style: google
            show_root_heading: true
            heading_level: 2
            show_symbol_type_toc: true

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true